# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdff75ce34cac9d2eb82c4e4ef1d4a26bb35920d080ac02dd8591924b4d3925dc760cd20505865b7ee18b3608348daced50d2f883dec56f7d27067691feb3435

test:
  secret_key_base: beb92c5502fac7f70621f0e0a2bc41f242c7ab5dde8b6257146bec362b417fc8e44e869bda5eb51f6676d1567c701c03b63b94599c064eac4adefb34888c693f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
